### ISSUE TITLE
Exception pri izmjeni nepostojećeg prodavača

### ISSUE THREAD

**Issue by esensar** [SoftverInzenjeringETFSA/SI2015Tim8#37]
Komponenta:
Izmjena prodavača

commit ID:
e890c1b

Opis problema:
Nedostatak poruke o neuspješnoj operaciji pri pokušaju izmjene obrisanog prodavača.

Koraci za reproduciranje problema:
1. Login kao master
2. Otvoriti tab za prodavače te kliknuti Dodaj i dodati prodavača
3. Vratiti se na glavnu formu, te kliknuti na dodanog prodavača i na izmjeni.
4. Obrisati tog prodavača bez gašenja forme za izmjenu
5. Klikom na izmjeni se ništa ne dešava

Dobijeni rezultat:
java.lang.NullPointerException
    at ba.unsa.etf.si.tim8.mlmarketing.ui.ProdavacDodajIzmjeni$2.actionPerformed(ProdavacDodajIzmjeni.java:227)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)

Očekivani rezultat:
Poruka o neuspješnoj/nemogućoj operaciji.

**Comment by encore13** [comment]
Popravljeno.
